### ISSUE TITLE
Feature 4 - User Can See Their Current Location

### ISSUE THREAD

**Issue by Andrew-M-A** [Andrew-M-A/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see their current location on map when they sign in.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While the user is signed in, they will see a view of a map and their current location on that map with a pulsing marker.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![FLASH! User Can See Location Mobile](https://user-images.githubusercontent.com/99862668/181394663-8db598ed-20e1-4490-8a33-00cdbb438273.jpg)

![FLASH! User Can See Location Desktop](https://user-images.githubusercontent.com/99862668/181394675-cb6cd90c-9f0f-4267-91a6-5120ede469d5.jpg)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to to render map
- [x] Use Geolocation API to get user's latitude and longitude (getCurrentPosition())
- [x] Update component when user's location changes (watchPosition())

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
