### ISSUE TITLE
Feature 5 - User Can See All Climbing Gyms on Map

### ISSUE THREAD

**Issue by Andrew-M-A** [Andrew-M-A/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see all Climbing Gyms in 15 mile radius on map.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see all climbing gyms within specified radius

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![FLASH! User Can See Location Mobile](https://user-images.githubusercontent.com/99862668/181395081-2d0be88c-3f90-4b9f-a0c5-3f1b4abe40f0.jpg)

![FLASH! User Can See Location Desktop](https://user-images.githubusercontent.com/99862668/181395068-f0b0d5d7-c238-4fc9-a1fb-68a16b873cf3.jpg)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] update this.state of HomeMap component to include a "gyms" property which will hold relevant gym info such as "latitude, longitude, and businessId"
- [x] Update HomeMap component to send a FETCH request to "Yelp Fusion API" on "componentDidMount"
- [x] use the 'latitude', longitude, and businessId' returned from Yelp Fusion API to generate markers on map

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
