### ISSUE TITLE
Feature 6 - User Can Get Directions to Climbing Gyms

### ISSUE THREAD

**Issue by Andrew-M-A** [Andrew-M-A/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to click on a climbing gym and get directions to it.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on a gym, they will have option to get directions for it.
If they do, they will be given driving directions to specified gym using Google Maps API

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![FLASH! User Can Get Directions Mobile](https://user-images.githubusercontent.com/99862668/181395897-de5b6402-fa1a-4fbc-8d48-7af49a859c6a.png)

![FLASH! User Can Get Directions Mobile 2](https://user-images.githubusercontent.com/99862668/181395899-3d6e1bef-1b12-42f4-9f60-9185cee93b46.png)

![FLASH! User Can Get Directions Desktop](https://user-images.githubusercontent.com/99862668/181395887-fac8d15f-f5df-480e-9606-460a129aab89.png)

![FLASH! User Can Get Directions Desktop 2](https://user-images.githubusercontent.com/99862668/181395894-d85a84c8-9f75-444e-9268-efd4f1ac5f23.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update renderMarkers function to add an onClick event to each marker that is rendered
- [x] when a marker is clicked, reveal an info bubble that says "Directions"
- [x] when "Directions" is clicked on, call a function that, along with the Google Directions API, gives the user directions to a climbing gym (will use user's current lat/lng and lat/lng of destination)
- [x] have route distance, duration, and time of arrival displayed

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
